#!/usr/bin/env julia
#
# Case 27 — PLASMA code-to-code dispersion comparison.
#
# Overlays our hybrid whistler dispersion ω(k) against NHDS, an external open-source
# kinetic plasma code (the New Hampshire Dispersion relation Solver, danielver02/NHDS,
# BSD-2), which solves the full hot-plasma Vlasov-Maxwell dispersion independently of
# our code. This is a genuine PHYSICS code-to-code comparison (unlike the FFTW/MPI/HDF5
# infrastructure checks) — the kind that can expose real bugs in the dispersion.
#
# Our side is the independent Hall-MHD eigenvalue oracle (test/oracles, HYB-006); NHDS
# is full kinetic. They must agree where the fluid closure is valid (high k, ω≪Ω_e),
# and the few-% spread near k·ρ_i~1 is the expected FLR/thermal fluid-vs-kinetic
# difference — reported, not hidden.
#
# NHDS source/binary/output are GITIGNORED (regenerated by build_nhds.sh). This
# all-validation case treats a missing or unparseable NHDS output as a failed
# validation, not a skip.

if !isdefined(@__MODULE__, :ValidationCase)
    include(joinpath(@__DIR__, "..", "common.jl"))
end
using HybridPlasmaPIC, Printf
if !isdefined(@__MODULE__, :HybridDispersionOracle)
    include(joinpath(@__DIR__, "..", "..", "test", "oracles", "hybrid_dispersion_oracle.jl"))
end
using .HybridDispersionOracle

function case_27_nhds_dispersion_comparison(artifact_dir::AbstractString)
    id = "27_nhds_dispersion_comparison"
    cat = "external_plasma_code"
    refkind = "external_plasma_code"
    ref = "NHDS (danielver02/NHDS, BSD-2) whistler.in: β=1 parallel Vlasov-Maxwell"
    nhds_out = joinpath(@__DIR__, "nhds_build", "NHDS", "output_whistler.in_plasma.dat")

    # regenerate the (gitignored) NHDS output if missing
    if !isfile(nhds_out)
        try
            run(`bash $(joinpath(@__DIR__, "build_nhds.sh"))`)
        catch
        end
    end
    if !isfile(nhds_out)
        artifact = joinpath(artifact_dir, "$(id).csv")
        rows = (("nhds_output_available_error", 1.0, 0.0, "absolute", 1.0, 0.0),)
        _write_metric_csv(artifact, rows)
        return _metric_rows_to_results(
            id = id,
            category = cat,
            reference_kind = refkind,
            reference = ref,
            rows = rows,
            artifact = artifact,
            notes = "NHDS not built (needs git+gfortran+make); run validation/27_nhds_dispersion_comparison/build_nhds.sh first.",
        )
    end

    # parse NHDS whistler ω(k)  (cols: k, theta, omega, gamma, species, ...)
    ks = Float64[]
    wn = Float64[]
    for ln in eachline(nhds_out)
        s = strip(ln)
        (isempty(s) || startswith(s, "#")) && continue
        f = split(s)
        length(f) < 5 && continue
        parse(Int, f[5]) == 1 || continue
        push!(ks, parse(Float64, f[1]))
        push!(wn, parse(Float64, f[3]))
    end
    if length(ks) < 5
        artifact = joinpath(artifact_dir, "$(id).csv")
        rows = (("nhds_output_parse_error", length(ks), 5.0, "margin", 5.0 - length(ks), 0.0),)
        _write_metric_csv(artifact, rows)
        return _metric_rows_to_results(
            id = id,
            category = cat,
            reference_kind = refkind,
            reference = ref,
            rows = rows,
            artifact = artifact,
            notes = "NHDS output unparseable or has too few whistler-branch points.",
        )
    end

    # our Hall-MHD whistler = the highest parallel branch (R-mode) at β=1
    cs = sqrt((5 / 3) * 0.5)                  # MHD sound speed at β=1 (P=0.5, ρ=1)
    wo = [maximum(dispersion_frequencies((0.0, 0.0, k), (0.0, 0.0, 1.0); cs = cs)) for k in ks]
    rel = abs.(wo .- wn) ./ wn
    hi = ks .>= 2.0                           # converged regime where fluid ≈ kinetic
    lo = .!hi                                  # thermal/FLR transition where kinetic differs more
    max_hi = maximum(rel[hi])
    max_all = maximum(rel)
    max_low = any(lo) ? maximum(rel[lo]) : NaN
    overlay_count_error = max(0.0, 5.0 - length(ks))
    flr_gap_error = max(0.0, 2 * max_hi - max_low)

    # overlay points (k, ω_NHDS, ω_oracle, rel_diff) for "lines near overlay" plotting — gitignored
    overlay = joinpath(artifact_dir, "$(id)_overlay.csv")
    _write_csv(
        overlay,
        ("k_dp", "omega_NHDS_kinetic", "omega_oracle_hallmhd", "rel_diff"),
        ((ks[i], wn[i], wo[i], rel[i]) for i = 1:length(ks)),
    )

    artifact = joinpath(artifact_dir, "$(id).csv")
    rows = (
        ("whistler_k_ge_2_vs_NHDS_rel_error", max_hi, 0.0, "relative", max_hi, 0.02),
        ("whistler_fullrange_vs_NHDS_rel_error", max_all, 0.0, "relative", max_all, 0.08),
        ("whistler_overlay_point_count_error", length(ks), 5.0, "margin", overlay_count_error, 0.0),
        (
            "whistler_lowk_FLR_gap_exceeds_highk_error",
            max_low,
            2 * max_hi,
            "ordering",
            flr_gap_error,
            0.0,
        ),
    )
    _write_metric_csv(artifact, rows)
    return _metric_rows_to_results(
        id = id,
        category = cat,
        reference_kind = refkind,
        reference = ref,
        rows = rows,
        artifact = artifact,
        notes = "Hall-MHD whistler is compared against the independent NHDS kinetic solver. Agreement is tight at k*d_p>=2, while the low-k thermal/FLR transition is allowed to differ more and must remain bounded.",
    )
end

VALIDATION_CASE = ValidationCase(
    id = "27_nhds_dispersion_comparison",
    default = false,
    description = "Whistler dispersion vs the external NHDS kinetic plasma solver (code-to-code overlay).",
    runner = case_27_nhds_dispersion_comparison,
)

if abspath(PROGRAM_FILE) == @__FILE__
    exit(
        _run_single_case_main(
            VALIDATION_CASE,
            ARGS;
            default_artifact_dir = joinpath(@__DIR__, "artifacts"),
        ),
    )
end
