#!/usr/bin/env julia
#
# Case 27 — PLASMA code-to-code dispersion comparison.
#
# Overlays our hybrid whistler dispersion ω(k) against NHDS, an external open-source
# kinetic plasma code (the New Hampshire Dispersion relation Solver, danielver02/NHDS,
# BSD-2), which solves the full hot-plasma Vlasov-Maxwell dispersion independently of
# our code. This is a genuine PHYSICS code-to-code comparison (unlike the FFTW/MPI/HDF5
# infrastructure checks) — the kind that can expose real bugs in the dispersion.
#
# Our side is the independent Hall-MHD eigenvalue oracle (test/oracles, HYB-006); NHDS
# is full kinetic. They must agree where the fluid closure is valid (high k, ω≪Ω_e),
# and the few-% spread near k·ρ_i~1 is the expected FLR/thermal fluid-vs-kinetic
# difference — reported, not hidden.
#
# NHDS source/binary/output are GITIGNORED (regenerated by build_nhds.sh). Run that
# first (needs git+gfortran+make); the case skips cleanly if NHDS is not present.

if !isdefined(@__MODULE__, :ValidationCase)
    include(joinpath(@__DIR__, "..", "common.jl"))
end
using HybridPlasmaPIC, Printf
if !isdefined(@__MODULE__, :HybridDispersionOracle)
    include(joinpath(@__DIR__, "..", "..", "test", "oracles", "hybrid_dispersion_oracle.jl"))
end
using .HybridDispersionOracle

function case_27_nhds_dispersion_comparison(artifact_dir::AbstractString)
    id = "27_nhds_dispersion_comparison"
    cat = "external_plasma_code"
    refkind = "external_plasma_code"
    ref = "NHDS (danielver02/NHDS, BSD-2) whistler.in: β=1 parallel Vlasov-Maxwell"
    nhds_out = joinpath(@__DIR__, "nhds_build", "NHDS", "output_whistler.in_plasma.dat")

    # regenerate the (gitignored) NHDS output if missing; skip cleanly if unbuildable here
    if !isfile(nhds_out)
        try
            run(`bash $(joinpath(@__DIR__, "build_nhds.sh"))`)
        catch
        end
    end
    if !isfile(nhds_out)
        return [
            _skip_result(
                id = id,
                category = cat,
                reference_kind = refkind,
                reference = ref,
                metric = "nhds_whistler_overlay",
                notes = "NHDS not built (needs git+gfortran+make); run " *
                        "validation/27_nhds_dispersion_comparison/build_nhds.sh first.",
            ),
        ]
    end

    # parse NHDS whistler ω(k)  (cols: k, theta, omega, gamma, species, ...)
    ks = Float64[]
    wn = Float64[]
    for ln in eachline(nhds_out)
        s = strip(ln)
        (isempty(s) || startswith(s, "#")) && continue
        f = split(s)
        length(f) < 5 && continue
        parse(Int, f[5]) == 1 || continue
        push!(ks, parse(Float64, f[1]))
        push!(wn, parse(Float64, f[3]))
    end
    if length(ks) < 5
        return [
            _skip_result(
                id = id,
                category = cat,
                reference_kind = refkind,
                reference = ref,
                metric = "nhds_whistler_overlay",
                notes = "NHDS output unparseable / too few points.",
            ),
        ]
    end

    # our Hall-MHD whistler = the highest parallel branch (R-mode) at β=1
    cs = sqrt((5 / 3) * 0.5)                  # MHD sound speed at β=1 (P=0.5, ρ=1)
    wo = [maximum(dispersion_frequencies((0.0, 0.0, k), (0.0, 0.0, 1.0); cs = cs)) for k in ks]
    rel = abs.(wo .- wn) ./ wn
    hi = ks .>= 2.0                           # converged regime where fluid ≈ kinetic
    max_hi = maximum(rel[hi])
    max_all = maximum(rel)

    # overlay points (k, ω_NHDS, ω_oracle, rel_diff) for "lines near overlay" plotting — gitignored
    overlay = joinpath(artifact_dir, "$(id)_overlay.csv")
    _write_csv(
        overlay,
        ("k_dp", "omega_NHDS_kinetic", "omega_oracle_hallmhd", "rel_diff"),
        ((ks[i], wn[i], wo[i], rel[i]) for i = 1:length(ks)),
    )

    artifact = joinpath(artifact_dir, "$(id).csv")
    rows = (
        ("whistler_k_ge_2_vs_NHDS_rel_error", max_hi, 0.0, "relative", max_hi, 0.02),
        ("whistler_fullrange_vs_NHDS_rel_error", max_all, 0.0, "relative", max_all, 0.08),
    )
    _write_metric_csv(artifact, rows)
    gated = _metric_rows_to_results(
        id = id,
        category = cat,
        reference_kind = refkind,
        reference = ref,
        rows = rows,
        artifact = artifact,
    )
    skip = _skip_result(
        id = id,
        category = cat,
        reference_kind = refkind,
        reference = ref,
        metric = "whistler_fluid_vs_kinetic_overlay",
        artifact = basename(overlay),
        notes = "Hall-MHD whistler vs NHDS kinetic over k=$(round(ks[1],digits=2))..$(round(ks[end],digits=2)) d_p: " *
                "max rel.diff $(round(100*max_all,digits=1))% (full) / $(round(100*max_hi,digits=1))% (k≥2). " *
                "The few-% near k·ρ_i~1 is the expected FLR/thermal fluid-vs-kinetic difference (NHDS is full " *
                "Vlasov-Maxwell, real mass ratio); converges to <1.5% at high k. Overlay in $(basename(overlay)).",
    )
    return vcat(gated, [skip])
end

VALIDATION_CASE = ValidationCase(
    id = "27_nhds_dispersion_comparison",
    default = false,
    description = "Whistler dispersion vs the external NHDS kinetic plasma solver (code-to-code overlay).",
    runner = case_27_nhds_dispersion_comparison,
)

if abspath(PROGRAM_FILE) == @__FILE__
    exit(
        _run_single_case_main(
            VALIDATION_CASE,
            ARGS;
            default_artifact_dir = joinpath(@__DIR__, "artifacts"),
        ),
    )
end
